name: First
on: [push]
jobs:
  job1:
    name: First job1
    runs-on: ubuntu-latest
    steps:
      -name: Step one
        uses: actions/checkout@v2
      -name: Step Two
        run: env | sort
  job2:
    name: Second job2
    runs-on: windows-latest
    steps:
      -name: Step one
        uses: actions/checkout@v2
      -name: Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"